services:
  - type: web
    name: mfh-tools-backend
    runtime: node
    repo: https://github.com/Falconmx1/mx_falconmx_security
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: HIBP_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
